### ISSUE TITLE
When customhelp cog is enabled I can't get help for commands.

### ISSUE THREAD

**Issue by Jackenmen** [NekoTony/Neko-Cogs#10]
Hi,
when I have customhelp cog enabled I can't get help for commands.
I mean my custom help works, but when I type for example "[p]help gif" I won't get a help for this command.
I come up with workaround, but you could simply add it to your code or if you want, you can give option to enable/disable it or even something more:

You need to add one argument to `help` command like this:
```
async def help(self, ctx, *, command=None):
```

And add this on the beginning of that command:

```
if command is not None:
    ctx.command = self.bot.get_command(command)
    await send_cmd_help(ctx)
    return
```

**Comment by NekoTony** [comment]
Make a pull request then

**Comment by Jackenmen** [comment]
Could you do that for me? I'm not familiar with github :/

22.09.2017 13:09 "NekoTony" <notifications@github.com> napisał(a):

**Comment by NekoTony** [comment]
No, sorry. Ask someone else.
